#! /bin/bash

#       __
#      / /_  _________ _      ____________
#     / __ \/ ___/ __ \ | /| / / ___/ ___/
#  _ / /_/ (__  ) /_/ / |/ |/ / /  / /__
# (_)_.___/____/ .___/|__/|__/_/   \___/
#             /_/

#  ===============================
#              CONFIGS            
#  ===============================

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         0
bspc config window_gap           20
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config external_rules_command ~/.config/bspwm/external-rules

#  =============================
#              RULES            
#  =============================

bspc rule -a "*" state=floating
bspc rule -a 'matplotlib' rectangle='963x800+2855+1308'
