#! /bin/bash

#     __                                    __                        __
#    / /_  _________ _      __   ___  _  __/ /____  _________  ____ _/ /
#   / __ \/ ___/ __ \ | /| / /  / _ \| |/_/ __/ _ \/ ___/ __ \/ __ `/ /
#  / /_/ (__  ) /_/ / |/ |/ /  /  __/>  </ /_/  __/ /  / / / / /_/ / /
# /_.___/____/ .___/|__/|__/   \___/_/|_|\__/\___/_/  /_/ /_/\__,_/_/
#           /_/

wid=$1
class=$2
instance=$3
consequences=$4

if grep 'marked=on' <<<$consequences; then
	case $class in
	  "Google-chrome")
			xprop -id "${wid}" -f WM_CLASS 8s -set WM_CLASS "ip-chrome"
			eval "$consequences"
			echo "state=floating"
	    ;;

	  "Subl")
			xprop -id "${wid}" -f WM_CLASS 8s -set WM_CLASS "ip-sublime"
			eval "$consequences"
			echo "state=floating rectangle=800x1000+1000+1000" # rectangle=WxH+X+Y

	    ;;

	  "Alacritty")
		title=$(xtitle "$wid")
		if [[ $title == 'ip-ranger' ]]; then
			xprop -id "${wid}" -f WM_CLASS 8s -set WM_CLASS "ip-ranger"
			eval "$consequences"
			echo "state=floating"
		elif [[ $title == 'ip-taskwarrior' ]]; then
			xprop -id "${wid}" -f WM_CLASS 8s -set WM_CLASS "ip-taskwarrior"
			eval "$consequences"
			echo "state=floating"

		elif [[ $title == 'ip-bash' ]]; then
			xprop -id "${wid}" -f WM_CLASS 8s -set WM_CLASS "ip-bash"
			eval "$consequences"
			echo "state=floating"
		fi
	    ;;
	esac
fi
